#!/bin/sh -e

# linux where i can see it
PREREQS="udev"

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

# mount /dev/mmcblk0p1 on the rootfs at /dev/sdcard
mkdir /dev/sdcard
mount -t vfat /dev/mmcblk0p1 /dev/sdcard
losetup /dev/loop0 /dev/sdcard/@@LIWIXI_IMAGE_FILENAME@@
